# Configuración del servidor
quarkus.http.port=8080

# Configuración del Cliente Redis Reactivo de Quarkus
# Por defecto se conecta a localhost:6379. 
# Para usar una base de datos en la nube (ej. Upstash), se puede cambiar esta propiedad o usar variables de entorno.
quarkus.redis.hosts=redis://localhost:6379
# En caso de requerir contraseña, se puede configurar así:
# quarkus.redis.password=tu_contraseña_aqui
